### PR TITLE
Improve readme

### PR DESCRIPTION
**Pull request by muniter**
Hello @windwp I really like this status line and would like to help with improving the documentation. In this case some typos in the readme. I'm not a native English speaker but like to help were I can. :)

I will add a few more when I'm on my PC since I'm on mobile.

### CODE REVIEW

**Comment by windwp** [comment]
hi thank for your PR.
just tell me when you finish

**Comment by muniter** [comment]
@windwp I'm done, ready for a review. 

I would also like to change the vaiable `show_in_active` and `in_active`in the code since the correct way is `show_inactive` and `inactive` this can be very confusing since it means the opposite of what it really does, but maybe in another PR.

**Comment by windwp** [comment]
hi many thank for that.
i already think that  name  show_in_active is not good. but when you change that it will break  config of user status

**Comment by muniter** [comment]
We could handle that by checking first for 'inactive' and it's `nil` then check `in_active` instead. 

That wouldn't break any existing status line and we can update the docs and samples.

**Pull request merged**
